<a href="https://colab.research.google.com/github/adelardw/Ionosphere-dataset/blob/main/Meteo_Ionosphere_Data_set_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [129]:
import pandas as pd
import numpy as np

In [130]:
!wget 'https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data'
# get on https://archive.ics.uci.edu/ml/datasets/Ionosphere
# or look at 8 example https://machinelearningmastery.ru/standard-machine-learning-datasets/

--2023-02-15 15:32:36--  https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 76467 (75K) [application/x-httpd-php]
Saving to: ‘ionosphere.data’

ionosphere.data     100%[===================>]  74.67K  --.-KB/s    in 0.1s

2023-02-15 15:32:36 (553 KB/s) - ‘ionosphere.data’ saved [76467/76467]

In [131]:
df = pd.read_csv('/content/ionosphere.data')

In [145]:
df

,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.1,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
0,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,0
1,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,1
2,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,0
3,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,1
4,1,0,0.02337,-0.00592,-0.09924,-0.11949,-0.00763,-0.11824,0.14706,0.06637,...,-0.01535,-0.03240,0.09223,-0.07859,0.00732,0.00000,0.00000,-0.00039,0.12011,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,1,0,0.83508,0.08298,0.73739,-0.14706,0.84349,-0.05567,0.90441,-0.04622,...,-0.04202,0.83479,0.00123,1.00000,0.12815,0.86660,-0.10714,0.90546,-0.04307,1
346,1,0,0.95113,0.00419,0.95183,-0.02723,0.93438,-0.01920,0.94590,0.01606,...,0.01361,0.93522,0.04925,0.93159,0.08168,0.94066,-0.00035,0.91483,0.04712,1
347,1,0,0.94701,-0.00034,0.93207,-0.03227,0.95177,-0.03431,0.95584,0.02446,...,0.03193,0.92489,0.02542,0.92120,0.02242,0.92459,0.00442,0.92697,-0.00577,1
348,1,0,0.90608,-0.01657,0.98122,-0.01989,0.95691,-0.03646,0.85746,0.00110,...,-0.02099,0.89147,-0.07760,0.82983,-0.17238,0.96022,-0.03757,0.87403,-0.16243,1
349,1,0,0.84710,0.13533,0.73638,-0.06151,0.87873,0.08260,0.88928,-0.09139,...,-0.15114,0.81147,-0.04822,0.78207,-0.00703,0.75747,-0.06678,0.85764,-0.06151,1

In [132]:
df['g'].replace(['b','g'],[0,1],inplace = True)

In [144]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 35 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   1          350 non-null    int64
 1   0          350 non-null    int64
 2   0.99539    350 non-null    float64
 3   -0.05889   350 non-null    float64
 4   0.85243    350 non-null    float64
 5   0.02306    350 non-null    float64
 6   0.83398    350 non-null    float64
 7   -0.37708   350 non-null    float64
 8   1.1        350 non-null    float64
 9   0.03760    350 non-null    float64
 10  0.85243.1  350 non-null    float64
 11  -0.17755   350 non-null    float64
 12  0.59755    350 non-null    float64
 13  -0.44945   350 non-null    float64
 14  0.60536    350 non-null    float64
 15  -0.38223   350 non-null    float64
 16  0.84356    350 non-null    float64
 17  -0.38542   350 non-null    float64
 18  0.58212    350 non-null    float64
 19  -0.32192   350 non-null    float64
 20  0.56971    350 non-null    float64
 21  -0.29674   350 non-null    float64
 22  0.36946    350 non-null    float64
 23  -0.47357   350 non-null    float64
 24  0.56811    350 non-null    float64
 25  -0.51171   350 non-null    float64
 26  0.41078    350 non-null    float64
 27  -0.46168   350 non-null    float64
 28  0.21266    350 non-null    float64
 29  -0.34090   350 non-null    float64
 30  0.42267    350 non-null    float64
 31  -0.54487   350 non-null    float64
 32  0.18641    350 non-null    float64
 33  -0.45300   350 non-null    float64
 34  g          350 non-null    int64
dtypes: float64(32), int64(3)
memory usage: 95.8 KB

In [134]:
df.corr()['g']

1            0.465322
0                 NaN
0.99539      0.518412
-0.05889     0.126496
0.85243      0.516027
0.02306      0.149658
0.83398      0.449769
-0.37708     0.210027
1.1          0.293415
0.03760      0.121382
0.85243.1    0.166718
-0.17755     0.161613
0.59755      0.181176
-0.44945     0.199894
0.60536      0.206557
-0.38223     0.151226
0.84356      0.085597
-0.38542     0.121191
0.58212      0.116788
-0.32192     0.036896
0.56971      0.218986
-0.29674    -0.115274
0.36946      0.204500
-0.47357     0.007896
0.56811      0.187722
-0.51171     0.003403
0.41078     -0.110663
-0.46168     0.044350
0.21266      0.250883
-0.34090    -0.002626
0.42267      0.294396
-0.54487    -0.033829
0.18641      0.262071
-0.45300    -0.062169
g            1.000000
Name: g, dtype: float64

In [135]:
feature = ['1', '0.99539', '0.85243', '0.83398', '0.60536', '0.56971','-0.44945', '0.36946', '0.21266', '0.42267', '0.18641']

In [136]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error as msee
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [137]:
X = df[feature]
y = df['g']

In [142]:
X_train,X_test,y_train, y_test = train_test_split(X,y, test_size = 0.2,random_state = 0)
logreg = LogisticRegression(max_iter = 2500)
logreg.fit(X_train,y_train)
y_pred = logreg.predict(X_test)

mse = msee(y_test,y_pred)

'1 - good meteo prognose, 0 - bad meteo prognose'
good_or_bad = 1
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, pos_label= good_or_bad)
recall = recall_score(y_test, y_pred, pos_label= good_or_bad)
f1 = f1_score(y_test, y_pred, pos_label= good_or_bad)

In [143]:
print(f'Mse: {mse}')
print("Accuracy: {}\nPrecision: {}\nRecall: {}\nF1-Score: {}".format(accuracy, precision, recall, f1))

Mse: 0.1
Accuracy: 0.9
Precision: 0.9111111111111111
Recall: 0.9318181818181818
F1-Score: 0.9213483146067416